; Script generated by Owner for Resonance App
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Build command: flutter build windows --release

#define MyAppName "Resonance"
#define MyAppVersion "0.1.2-beta"
#define MyAppNumericVersion "0.1.2.0"
#define MyAppPublisher "ChronoTech"
#define MyAppURL "https://github.com/ChronoTcs/Resonance"
#define MyAppExeName "Resonance.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3F7A1E1-8C9B-4B2E-BC6D-9E9A9B9C9D9E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=Resonance-v{#MyAppVersion}-Windows
Compression=lzma2/ultra64
CloseApplications=force
SetupIconFile=..\windows\runner\resources\app_icon.ico
SolidCompression=yes
WizardStyle=modern

; Version Info properties for Windows PE resource header
VersionInfoVersion={#MyAppNumericVersion}
VersionInfoTextVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppName} Setup
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppNumericVersion}
VersionInfoProductTextVersion={#MyAppVersion}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; AppUserModelID: "com.chronostudio.Resonance"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; AppUserModelID: "com.chronostudio.Resonance"

[Run]
; Always relaunch after silent in-app update (/VERYSILENT mode)
Filename: "{app}\{#MyAppExeName}"; Flags: nowait runasoriginaluser; Check: WasInAppUpdate
; Show "Launch Resonance" checkbox in wizard for fresh/manual installs
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Returns true when installer was launched with /RELAUNCH switch (in-app update)
function WasInAppUpdate: Boolean;
begin
  Result := ExpandConstant('{param:RELAUNCH|0}') = '1';
end;
